sb_api_advanced_access: True
sb_task_status_refresh_period: 20
fastq_project: lizhang/adk-resources
apps:
  bwa: lizhang/adk-resources/bwa-mem-multi-lane/8
  trimgalore: admin/sbg-public-data/trim-galore/6
  markdup: admin/sbg-public-data/picard-markduplicates-1-140/3
  alignmentqc: admin/sbg-public-data/picard-collectalignmentsummarymetrics-1-140/7
reference_files:
  bwa_bundle: admin/sbg-public-data/human_g1k_v37_decoy.fasta.tar
  reference_fasta: admin/sbg-public-data/human_g1k_v37_decoy.fasta 
qc:
  min_pct_pf_reads_aligned: 0.998
  min_strand_balance: 0.49
  min_fastq_size: 5500000
skip_duplicate_marking: false
